# Generated by Django 3.2 on 2022-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=10)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created on date')),
                ('subject', models.IntegerField(choices=[('Order status', 'Order status'), ('Payment', 'Payment'), ('Complaints', 'Complaints'), ('Other', 'Other'), ('Products', 'Products')], default=1)),
            ],
        ),
    ]
