# Generated by Django 3.2 on 2022-01-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(choices=[('Order status', 'Order status'), ('Products', 'Products'), ('Complaints', 'Complaints'), ('Payment', 'Payment'), ('Other', 'Other')], default=1),
        ),
    ]
