# Generated by Django 3.2 on 2022-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220122_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(choices=[('Complaints', 'Complaints'), ('Order status', 'Order status'), ('Products', 'Products'), ('Other', 'Other'), ('Payment', 'Payment')], default=1),
        ),
    ]
