# Generated by Django 3.2 on 2022-01-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
