# Generated by Django 3.2 on 2022-01-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcomment_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='author',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
