# Generated by Django 3.2 on 2022-01-26 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
