# Generated by Django 3.2 on 2022-01-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productcomment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
